package com.leecardo.paymentdiagnostics.domain;

/**
 * Stable identifier for a diagnosis rule result.
 */
public enum DiagnosisRuleId {
    NO_KNOWN_EXCEPTION,
    PAYMENT_NOT_STARTED,
    PAYMENT_PROCESSING_TIMEOUT,
    PROVIDER_SUCCEEDED_CALLBACK_MISSING,
    CALLBACK_SUCCEEDED_ORDER_NOT_UPDATED,
    PAYMENT_FAILED_WITH_PROVIDER_ERROR,
    MESSAGE_NOT_SENT,
    MESSAGE_SEND_FAILED,
    MESSAGE_NOT_CONSUMED,
    MESSAGE_CONSUME_FAILED,
    COMPENSATION_NOT_CREATED,
    COMPENSATION_FAILED,
    COMPENSATION_RETRIES_EXHAUSTED,
    TRACE_MISSING,
    INSUFFICIENT_EVIDENCE
}
